### ISSUE TITLE
crash with im use proxy

### ISSUE THREAD

**Issue by Egra228** [AnAverageBeing/XDDOS#7]
cmd line java -jar XDDOS.jar 65.21.114.241:25565 760 MOTD 360 100 y -noansi
error:
[XDDOS]  Parsing proxy...
Exception in thread "main" java.lang.IllegalArgumentException: Malformed URL: 203.229.251.191:80
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:131)
        at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:70)
        at org.jsoup.Jsoup.connect(Jsoup.java:73)
        at XD.XDDOS.utils.proxy.ProxyGen.lambda$0(ProxyGen.java:33)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at XD.XDDOS.utils.proxy.ProxyGen.<init>(ProxyGen.java:31)
        at XD.XDDOS.utils.helper.ArgsHelper.OneLine(ArgsHelper.java:107)
        at XD.XDDOS.XDDOS.main(XDDOS.java:74)
Caused by: java.net.MalformedURLException: no protocol: 203.229.251.191:80
        at java.base/java.net.URL.<init>(URL.java:674)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:129)
        ... 8 more

**Comment by LastKnell** [comment]
what did u put in ur urls.txt file

**Comment by AnAverageBeing** [comment]
U have to put links to scrape proxies from in urls.txt not the proxies itself
